spring:
  application:
    name: patrol-report-system

  mail:
    host: smtp.gmail.com
    port: 587
    username: patrolreportsystem@somemail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

report:
  email:
    recipient: supervisor@outlook.com

server:
  address: 0.0.0.0
  port: 8080